//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public string Name { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<int> SupplierCompanyId { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
